load("@io_bazel_rules_scala//scala:scala.bzl", "scala_library", "scala_binary", "scala_test")

scala_library(
    name = "Guava1",
    srcs = [
        "Guava1.scala",
        ]
    )

scala_library(
    name = "Guava2",
    srcs = [
        "Guava2.scala",
        ]
    )
