load("@io_bazel_rules_scala//scala:scala.bzl", "scala_library")


scala_library(
    name="Guava1",
    srcs=[
        "Guava1.scala",
    ],
    deps=[
        "@maven//:org_mockito_mockito_all_1_10_19",
    ],
)
