load("jvm_export.bzl", "jvm_export_version")

exports_files(
    glob([
        "*.bzl",
    ]),
    visibility = ["//visibility:public"],
)

jvm_export_version(
    name = "version",
    version = "0.0.0",
)
